# Generated by Django 5.2.7 on 2025-11-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_edit_date_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.ImageField(default='placeholder.png', upload_to='post_title_images'),
        ),
    ]
